import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#FFFFFF",
        padding: 12,
    },
    
    listSection: {
        flex: 0.55, 
        backgroundColor: "#f8f9fa",
        borderRadius: 12,
        padding: 12,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: "#e9ecef",
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    selectedSection: {
        flex: 0.45, 
        backgroundColor: "#f8f9fa",
        borderRadius: 12,
        padding: 12,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: "#e9ecef",
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    sectionHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: "#dee2e6",
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#212529",
        marginLeft: 8,
        flex: 1,
    },
    pageInfo: {
        fontSize: 12,
        color: "#6c757d",
        marginLeft: 'auto',
        backgroundColor: "#e9ecef",
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 10,
    },
    selectedCount: {
        fontSize: 12,
        color: "#6c757d",
        marginLeft: 4,
        backgroundColor: "#d1ecf1",
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 8,
    },
    listContainer: {
        height: 350, 
    },
    selectedListContainer: {
        flex: 1,
    },
    listContent: {
        paddingBottom: 4,
    },
    selectedListContent: {
        paddingBottom: 4,
    },
    
    itemContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 12,
        backgroundColor: "#ffffff",
        marginBottom: 6,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
        elevation: 1,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
    itemContent: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
    },
    avatarContainer: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: "#dc3545",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 12,
        elevation: 2,
        shadowColor: "#dc3545",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    selectedAvatar: {
        backgroundColor: "#28a745",
        shadowColor: "#28a745",
    },
    avatarText: {
        color: "#ffffff",
        fontSize: 14,
        fontWeight: "bold",
    },
    itemDetails: {
        flex: 1,
        paddingRight: 8,
    },
    itemName: {
        fontSize: 14,
        fontWeight: "600",
        color: "#212529",
        marginBottom: 2,
    },
    itemMatricula: {
        fontSize: 12,
        color: "#6c757d",
    },
    
    // Action buttons
    addButton: {
        backgroundColor: "#28a745",
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
        elevation: 2,
        shadowColor: "#28a745",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    removeButton: {
        backgroundColor: "#dc3545",
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
        elevation: 2,
        shadowColor: "#dc3545",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    
    selectedItemContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 12,
        backgroundColor: "#d1ecf1",
        marginBottom: 6,
        borderRadius: 8,
        borderLeftWidth: 4,
        borderLeftColor: "#17a2b8",
        elevation: 1,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
    selectedItemName: {
        fontSize: 14,
        fontWeight: "600",
        color: "#0c5460",
        marginBottom: 2,
    },
    selectedItemMatricula: {
        fontSize: 12,
        color: "#5a6c7d",
    },
    
    emptyContainer: {
        alignItems: "center",
        justifyContent: "center",
        padding: 24,
        backgroundColor: "#f8f9fa",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#dee2e6",
        borderStyle: "dashed",
    },
    emptyText: {
        color: "#6c757d",
        fontSize: 14,
        fontStyle: "italic",
    },
    
    // Pagination controls
    paginationControls: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: "#dee2e6",
    },
    pageButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#007bff",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 6,
        elevation: 2,
        shadowColor: "#007bff",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    pageButtonText: {
        color: "#ffffff",
        fontSize: 12,
        fontWeight: "600",
        marginHorizontal: 4,
    },
    disabledButton: {
        backgroundColor: "#6c757d",
        elevation: 0,
        shadowOpacity: 0,
    },
    disabledText: {
        color: "#ffffff",
        opacity: 0.7,
    },
});